dataset_name: 'PubMed'
task: 'LinkPrediction'
metrics: ['hits@10','hits@50','hits@100','acc','auc','roc_auc']
track_metric: 'roc_auc'

DIM: 16

DownStream:
  saved_embeddings: False
  using_features: True
  use_spectral: False
  random: False
  K: ${dataset.DIM}
  training:
    epochs: 300
    num_layers: 2
    dropout: 0.0
    lr: 0.01
    hidden_channels: 16
    batch_size: 1024

Node2Vec:
  training:
    embedding_dim: ${dataset.DIM}
    walk_length: 80
    context_size: 20
    walks_per_node: 10
    epochs: 20
    lr: 0.01
    batch_size: 1024
    num_negative_samples: 1
    sparse: True
    num_workers: 4

GNN:
  model: 'GraphSage'
  extra_info: False
  use_spectral: False
  K: ${dataset.DIM}
  training:
    hidden_channels: ${dataset.DIM}
    num_layers: 2
    dropout: 0.0
    lr: 0.01
    epochs: 200
    batch_size: 1024
    weight_decay: 0.000001


Shallow:
  training:
    lr: 0.01
    epochs: 500
    init_beta: 0.0
    embedding_dim: ${dataset.DIM}
    init: 'laplacian'
    decode_type: 'dist'
    batch_size: 1024
    train_batch: True
    weight_decay: 0.000001


combined:
  type: 'LogitsIntegration'
  LogitsIntegration:
    training:
      shallow_lr: 0.01
      init_beta: 0.0
      embedding_dim: ${dataset.DIM}
      init: 'laplacian'
      decode_type: 'dist'
      weight_decay_shallow: 0.000001


      deep_model: 'GAT'
      deep_hidden_channels: ${dataset.DIM}
      deep_lr: 0.01
      deep_out_dim: ${dataset.DIM}
      deep_num_layers: 2
      deep_dropout: 0.0
      weight_decay_deep: 0.0

      balance: False
      warm_start: 100
      joint_train: 200
      shallow_lr_joint: 0.01
      deep_lr_joint: 0.01
      lambda_lr: 0.01
      lambda_: 1.0
      batch_size: 1024
      direction: 'deep_first'
      shallow_frozen_epochs: 100
      deep_frozen_epochs: 100
      MLP_HIDDEN_CHANNELS: 16

  CombinedLatents:
    training:
      shallow_lr: 0.01
      init_beta: 0.0
      embedding_dim: ${dataset.DIM}
      init: 'laplacian'
      decode_type: 'dist'
      weight_decay_shallow: 0.000001


      deep_model: 'GCN'
      deep_hidden_channels: ${dataset.DIM}
      deep_lr: 0.01
      deep_out_dim: ${dataset.DIM}
      deep_num_layers: 2
      deep_dropout: 0.0

      warm_start: 100
      joint_train: 100
      shallow_lr_joint: 0.01
      deep_lr_joint: 0.01
      batch_size: 1024
      direction: 'deep_first'
      shallow_frozen_epochs: 0
      deep_frozen_epochs: 100


      MLP_HIDDEN_CHANNELS: 8
      MLP_LAYERS: 2
      MLP_DROPOUT: 0.0
